// <auto-generated />
namespace EventMangementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addispaidondamagereport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addispaidondamagereport));
        
        string IMigrationMetadata.Id
        {
            get { return "202410210338241_add-ispaid-ondamage-report"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
